#!/usr/bin/env python

import sys
import csv
import operator
import os
import pwd

"""
Very simple Python filter to collect stats from pwalk output.
use as a template to create other filters

Read csv file generated by pwalk and output the biggest users
"""

_version_ = '1.0.0'
_author_ = 'jfdey@fredhutch.org'

# pwalk fields
fields = ['inode', 'parent-inode', 'directory-depth', 'filename', 'extension',
 'UID', 'GID', 'st_size', 'st_dev', 'st_blocks"', 'st_nlink', '"st_mode"',
 'atime', 'mtime', 'ctime', 'fcount', 'sum']

def sizeof_fmt(num, suffix='B'):
    for unit in ['','Ki','Mi','Gi','Ti','Pi','Ei','Zi']:
        if abs(num) < 1024.0:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= 1024.0
    return "%.1f%s%s" % (num, 'Yi', suffix)


def basic_report():
    """ list all users by total amount of storage used and file count """
    users = {}
    file_count = {}
    dirSize = {}
    with open(sys.argv[1]) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',', quotechar='"')
        for row in csv_reader:
            uid = row[fields.index('UID')]
            fcount = int(row[fields.index('fcount')])
            sum = int(row[fields.index('sum')])
            filename = row[fields.index('filename')]
            if uid in users:
                users[uid]['sum'] += int(row[fields.index('st_size')])
                users[uid]['fcount'] += 1
            else:
                users[uid] = {}
                users[uid]['sum'] = int(row[fields.index('st_size')])
                users[uid]['fcount'] = 1
            if fcount > 2000:
                file_count[filename] = fcount
            if sum > 2500000000000:  # about 250GB
                dirSize[filename] = sum

    # create new hash to be sorted by size
    summary = {}
    for user in users:
        summary[user] = users[user]['sum']

    # sorted_size is list of tuples (uid, size)
    sorted_size = sorted(summary.items(), key=operator.itemgetter(1))

    for user in sorted_size:
        try:
            uname = pwd.getpwuid(int(user[0])).pw_name
        except KeyError:
            uname = user[0]
        print('{} UID: {} FileCount: {}'.format(user[1], uname, users[user[0]]['fcount']))

    sorted_fcount = dict(sorted(file_count.items(), key=lambda item: item[1]), reverse=True)
    print()
    print('Directories with large size amounts of storage')
    for k, v in sorted_fcount.items():
        print('{:15} {}'.format(v, k))

    # Dierectories with large sum of file sizes
    # Directories with large file size

    sorted_dirSize = dict(sorted(dirSize.items(), key=lambda item: item[1]), reverse=True)
    print()
    print('Directories with large number of files')
    for k, v in sorted_dirSize.items():
        print('{:8} {}'.format(sizeof_fmt(v),k))


if __name__ == '__main__':
    basic_report()
